name: Frontend CI

on:
  push:
    paths:
      - 'food-delivery-app/**'
  pull_request:
    paths:
      - 'food-delivery-app/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: food-delivery-app
        run: npm install

      - name: Build Angular app
        working-directory: food-delivery-app
        run: npm run build
